### ISSUE TITLE
第一行是不是错了啊。。。

### ISSUE THREAD

**Issue by laincat** [gfwlist/tinylist#1]
`
[Tinylist] **<-----这里!**
! Checksum: eYi37Ev/axOw6k10hO0ORw
! Expires: 1d
! Title: Tiny GFWList
! Scaled-down version of GFWList
! Last Modified: Thu, 14 Apr 2016 12:15:45 +0800
!
! HomePage: https://github.com/gfwlist/tinylist
! License: https://raw.githubusercontent.com/gfwlist/tinylist/master/COPYING.txt
!
! GFWList is bloated, some people don't feel
! good about it. Please contact us regarding
! URL submission / removal, or suggestion /
! enhancement at issue tracker:
! https://github.com/gfwlist/tinylist/issues/.

`

**Comment by cicku** [comment]
部分实现通过判断第一行是否为AutoProxy决定文件是否有效，可能不兼容。

**Comment by cicku** [comment]
第一行，甚至是原gfwlist本身的第一行，可能在今后还会变动，暂未确定。

**Comment by cicku** [comment]
暂时恢复。
