### ISSUE TITLE
啥时候再更新呢？挺喜欢这个tinylist的

### ISSUE THREAD

**Issue by ydq** [gfwlist/tinylist#3]
比原有的gfwlist要小巧的多，而且对于非重度和强迫症患者来说tinylist绝对是首选了。
貌似好久都没更新了，里面有个||chrome.com重复了，看着难受，希望可以更新一下，嘻嘻~

**Comment by cicku** [comment]
好的，近期我整理整理，更新一下。

**Comment by cicku** [comment]
今天更新了一下，加入了一些常用网址，如有建议欢迎提出。
