### ISSUE TITLE
beeg video Requires ahcdn.com as a combination

### ISSUE THREAD

**Issue by AmberisMyShiba** [gfwlist/tinylist#4]
Hi,I noticed the tinylist have some lists for porn website.One of them is beeg.When I use tinylist with my proxy for watching beeg‘s viedo.The Fluency of viedo is not good.Video playback offen paused and delayed.
I  suggest adding **_[||ahcdn.com]_**to the tinylist. And I confirmed this is useful.

BTW, pin-cong.com is a good common Chinese website like zhihu.com for free  Q&A,But now it's blocked for GWF. I highly recommended add pin-cong in tinylist.

Finally, thanks for the author's contribution

**Comment by cicku** [comment]
I will hand ahcdn over to cdnlist project, but probably with some delay, it's not blocked, so I could not add it.

**Comment by cicku** [comment]
819bade should address the problem of pin-cong.

**Comment by AmberisMyShiba** [comment]
thanks for repley.
